### PR TITLE
Remove extra files

### PR DESCRIPTION
**Pull request by ScottSWu**
* Add .DS_Store to gitignore
* The root repo directory should not be a python module

### CODE REVIEW

**Comment by anmolkabra** [comment]
why should the root repo dir not be a python module? Have you run the repo after these deletions?

**Comment by ScottSWu** [comment]
`__init__.py` makes the current folder a python module. If it's in the root folder then you would be able to do `import cs-minibot.minibot` which we shouldn't do.

**Comment by anmolkabra** [comment]
Have you tried running the gui/main.py from cs-minibot/ after this deletion? I don't know if it'll work

**Comment by ScottSWu** [comment]
Works fine for me. Please add tests if this is a concern.

If the concern is with PYTHONPATH and import errors, some people have been trying to run main.py while IN the gui folder. PYTHONPATH should refer to the root repo directory.

```
.../cs-minibot $ PYTHONPATH=. python gui/main.py
```
or
```
.../cs-minibot/gui $ PYTHONPATH=.. python main.py
```

**Comment by ScottSWu** [comment]
bump

**Review by chynu — COMMENTED** [review]
lgtm

**Review by chynu — APPROVED** [review]

**Pull request merged**
